--- 
id: basics
name: Les bases de Remix
summary: Un flux de travail typique dans Remix
level: 1
tags: 
  - Remix
steps:
  - name: Introduction à l'interface 
    path: interface_introduction
  - name: Introduction aux workspaces 
    path: workspaces
  - name: Chargement et compilation
    path: load_and_compile
  - name: Deploiement sur la VM Remix
    path: deploy_to_the_remixvm
  - name: Interaction avec les Functions
    path: interacting
  - name: Deploiement sur les réseaux blockchains publiques
    path: deploy_injected